- name: Installing nginx with apt
  apt:
    name: nginx
    state: latest

- name: Install nginx config
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default

- name: reload nginx service
  service:
    name: nginx
    state: reloaded
