- hosts: all
  roles:
    - common

- hosts: upldrg
  roles:
    - gpu
    - ipfs
    - ipfs-uploader
    - nginx
    - certbot

- hosts: upldr
  roles:
    - ipfs
    - ipfs-uploader
    - nginx
    - certbot

- hosts: saver
  roles:
    - ipfs
    - maria

- hosts: snap
  roles:
    - ipfs
    - ipfs-uploader
    - nginx
    - certbot

- hosts: zabbix
  roles:
    - zabbix
