- name: Download ipfs-updater
  get_url:
    url: https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
    dest: /tmp/ipfs-update.tar.gz
    checksum: sha256:d6430f832bcdc1aff16351f8ff894143d2e072d7dd3cc31f1ac6592e0528cca3
    mode: 0777

- name: Extracting ipfs-uploader
  unarchive:
    src: /tmp/ipfs-update.tar.gz
    dest: /home/dabbott/
  ignore_errors: true

- name: Running ipfs-upgrade latest
  command: /home/dabbott/ipfs-update/ipfs-update install latest
  args:
    creates: /usr/local/bin/ipfs
