- name: Changing permissions on ipfs binary making it heimindanger:dtube 0770
  file:
    path: /usr/local/bin/ipfs
    owner: heimindanger
    group: dtube
    mode: 0777


- name: Running ipfs init
  command: /usr/local/bin/ipfs init
  args:
    creates: /home/heimindanger/.ipfs/config
  become: true
  become_user: heimindanger

- name: Starting ipfs tmux session as heimindanger (may fail when session already exists)
  command: tmux new -d -s ipfs
  become: true
  become_user: heimindanger
  ignore_errors: yes

- name: Starting ipfs daemon in afforementioned tmux session as heimindanger
  command: tmux send -t ipfs.0 "IPFS_FD_MAX=32768 ipfs daemon" ENTER
  become: true
  become_user: heimindanger
