- name: Installing python so Ansible can run first time
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- name: Downloading Nodejs 9.x installation script
  get_url:
    url: https://deb.nodesource.com/setup_9.x
    checksum: sha256:58cc07fc167b95af418c88580f9ae31d275e88cb2397d5bb270e19e7f298cddc
    mode: 0777
    dest: /home/dabbott/setup.sh

- name: Installing Nodejs
  command: /home/dabbott/setup.sh
  args:
    creates: /usr/bin/npm
  become_user: root

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 43200

- name: Installing common tools with apt
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'sudo'
    - 'curl'
    - 'wget'
    - 'htop'
    - 'nload'
    - 'locate'
    - 'vim'
    - 'zabbix-agent'
    - 'tmux'
    - 'acl'
    - 'net-tools'
    - 'nodejs'
    - 'ffmpeg'
