- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become: true
  become_method: su

- name: Install bootstrapping Deps (Curl, Sudo, Wget)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'sudo'
    - 'curl'
    - 'wget'
    - 'htop'
    - 'nload'
    - 'locate'
    - 'vim'
    - 'zabbix-agent'
    - 'tmux'
  become: true
  become_method: su
