---
-
  tasks:
  - name: Installing users, keys and dtube group
  group:
      name: dtube
      state: present
  user:
      name: "{{ item }}"
      shell: /bin/bash
      group: dtube
    with_items:
      - dabbott
      - heimindanger
  authorized_key:
      user: dabbott
      state: present
      manage_dir: yes
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF/suWYXT8eekUrkoRyOH+m08JFc0mNuREAMc6vH1p4b/RPP98Zvs6lcAsnR6Odb4v+WOI7nrxNWFomRaM8aRl9+OmaGDJi/nPyc3cCxH0KEk3EvXn+qocOosGqMAUbSgfQBaH8Ee86+KEyIrQ4jV2xPOc2Mand+iNnU5XKiFthQ1WOAiDjDepS6tpssnCCWN6N5C0aCwussePTh4rbEl4FXZcK5BdcCRK2Lq5z7g+D29g2Eip16V1/r4ZVa4op5FP3LSlJN8KjIQXc8h+1BuAQjeE8+DzMSiIOP3hfby+ovOciudR+kIxePSWiovlvtnrjLJ+SfXZ+FB0ju5YKYmP dabbott"
  authorized_key:
      user: heimindanger
      state: present
      manage_dir: yes
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWSLsT95A+hsph+fiBHKmIKN32GE2/OLK+vviKGQBBKWIXQ79NsqlVkeQEOjm2J8Zc135mkQO5DbQsjAyl+DsvjMllCCbhRakdelAOfPdiox4E7wIM4P+ppH9eJC5QlEGPgufklLSXSeO1ihSINtQWhcmPuniH8wbHhVTYJTAuywE5kACUaZKj4FB+Jjh5sZIOp9KR7e5+AtwNQOcSucj/xj9Vk4hd8IO9j1zhCKupIIlOAiP0RZXJ9WlUdsV3bAVFrbQEk9Z7P1Sghxblclmx6lVHQ8unKGj+1gUMaJfuqzVDeKu8j5EBCucBvqitEUX0wkrJ1WDjQx/7xn7IQy9d heimindanger"
  authorized_key:
        user: root
        state: present
        manage_dir: yes
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF/suWYXT8eekUrkoRyOH+m08JFc0mNuREAMc6vH1p4b/RPP98Zvs6lcAsnR6Odb4v+WOI7nrxNWFomRaM8aRl9+OmaGDJi/nPyc3cCxH0KEk3EvXn+qocOosGqMAUbSgfQBaH8Ee86+KEyIrQ4jV2xPOc2Mand+iNnU5XKiFthQ1WOAiDjDepS6tpssnCCWN6N5C0aCwussePTh4rbEl4FXZcK5BdcCRK2Lq5z7g+D29g2Eip16V1/r4ZVa4op5FP3LSlJN8KjIQXc8h+1BuAQjeE8+DzMSiIOP3hfby+ovOciudR+kIxePSWiovlvtnrjLJ+SfXZ+FB0ju5YKYmP dabbott"
  lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%dtube'
        line: '%dtube ALL=(ALL) NOPASSWD: ALL'
        create: true


  - name: Update and upgrade apt packages
  become: true
  become_method: su
  apt:
    upgrade: yes
    update_cache: yes

  - name: Install bootstrapping Deps (Curl, Sudo, Wget)
    apt:
      name: "{{ items }}"
      state: latest
    with_items:
      - 'sudo'
      - 'curl'
      - 'wget'
