- name: Installing "dtube" group
  group:
      name: dtube
      state: present


- name: Installing user accounts for Heimindanger and Dabbott
  user:
      name: "{{ item }}"
      shell: /bin/bash
      group: dtube
  with_items:
    - 'dabbott'
    - 'heimindanger'
    - 'root'


- name: Installing dabbott key for dabbott user
  authorized_key:
      user: dabbott
      state: present
      manage_dir: yes
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF/suWYXT8eekUrkoRyOH+m08JFc0mNuREAMc6vH1p4b/RPP98Zvs6lcAsnR6Odb4v+WOI7nrxNWFomRaM8aRl9+OmaGDJi/nPyc3cCxH0KEk3EvXn+qocOosGqMAUbSgfQBaH8Ee86+KEyIrQ4jV2xPOc2Mand+iNnU5XKiFthQ1WOAiDjDepS6tpssnCCWN6N5C0aCwussePTh4rbEl4FXZcK5BdcCRK2Lq5z7g+D29g2Eip16V1/r4ZVa4op5FP3LSlJN8KjIQXc8h+1BuAQjeE8+DzMSiIOP3hfby+ovOciudR+kIxePSWiovlvtnrjLJ+SfXZ+FB0ju5YKYmP dabbott"

- name: Installing heimindanger key for heimindanger user
  authorized_key:
      user: heimindanger
      state: present
      manage_dir: yes
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWSLsT95A+hsph+fiBHKmIKN32GE2/OLK+vviKGQBBKWIXQ79NsqlVkeQEOjm2J8Zc135mkQO5DbQsjAyl+DsvjMllCCbhRakdelAOfPdiox4E7wIM4P+ppH9eJC5QlEGPgufklLSXSeO1ihSINtQWhcmPuniH8wbHhVTYJTAuywE5kACUaZKj4FB+Jjh5sZIOp9KR7e5+AtwNQOcSucj/xj9Vk4hd8IO9j1zhCKupIIlOAiP0RZXJ9WlUdsV3bAVFrbQEk9Z7P1Sghxblclmx6lVHQ8unKGj+1gUMaJfuqzVDeKu8j5EBCucBvqitEUX0wkrJ1WDjQx/7xn7IQy9d heimindanger"

- name: Installing second heimindanger key for heimindanger user
  authorized_key:
      user: heimindanger
      state: present
      manage_dir: yes
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsyo1jTNmMFYeSH7TiPxZZb4KH07p2SawL8TOv+EkXPtfRSt4eA9cSlYKbKPPX3oc4cZ+L6oFiwd2iuRRxx+7f9w0eANLw0k8cw4xWYITyhp/Ys62zr40B/VrOn04DVNLab7m6IK6MHMMOr18SlzuxUTQF2EGUL+L7mR5YxTZRT62oVehOg+STYtvdBMsZKH22UR78MPfTt6KWHQzZuG0xxGVR6C5aNULCfagDzeAS4uaYVQmWjg+6ryApQW3RIz12JJDcNYqNn09AuLblitW3ohV8aoRAqEteoaPGAClDrTByIAI1pPciS87Vo9Yviar2+lB6+zTyC0sN/D2L6kQf adrien@d.tube"

- name: Installing Dabbott key for root user
  authorized_key:
        user: root
        state: present
        manage_dir: yes
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF/suWYXT8eekUrkoRyOH+m08JFc0mNuREAMc6vH1p4b/RPP98Zvs6lcAsnR6Odb4v+WOI7nrxNWFomRaM8aRl9+OmaGDJi/nPyc3cCxH0KEk3EvXn+qocOosGqMAUbSgfQBaH8Ee86+KEyIrQ4jV2xPOc2Mand+iNnU5XKiFthQ1WOAiDjDepS6tpssnCCWN6N5C0aCwussePTh4rbEl4FXZcK5BdcCRK2Lq5z7g+D29g2Eip16V1/r4ZVa4op5FP3LSlJN8KjIQXc8h+1BuAQjeE8+DzMSiIOP3hfby+ovOciudR+kIxePSWiovlvtnrjLJ+SfXZ+FB0ju5YKYmP dabbott"

- name: Setting nopasswd sudo privileges
  lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%dtube'
        line: '%dtube ALL=(ALL) NOPASSWD: ALL'
        create: true
