- name: Exporting environment variable for cpu hosts
  lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^ASPNETCORE_ENVIRONMENT=prod_cpu'
        line: 'ASPNETCORE_ENVIRONMENT=prod_cpu'
        create: true
  when: ansible_distribution_major_version == "9"

- name: Copying ipfs-uploader from local host
  copy:
    src: ipfs-uploader.zip
    dest: /home/heimindanger/ipfs-uploader.zip
    mode: 0777
  become: true
  notify: new ipfs-uploader

- name: Changeing permissions on ipfs-uploader directory making it heimindanger:dtube 0770
  file:
    path: /home/heimindanger/ipfs-uploader/
    owner: heimindanger
    group: dtube
    mode: 0770
    recurse: yes

- name: Starting upldr tmux session as heimindanger (may fail when session already exists)
  command: tmux new -d -s upldr
  become: true
  become_user: heimindanger
  become_method: sudo
  ignore_errors: yes


- name: Moving tmux session working directory to /home/heimindanger/ipfs-uploader/Uploader.Web/
  command: tmux send -t upldr.0 "cd /home/heimindanger/ipfs-uploader/Uploader.Web/" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo

- name: Starting ipfs-uploader in afforementioned tmux session as heimindanger as a GPU instance
  command: tmux send -t upldr.0 "ASPNETCORE_ENVIRONMENT=prod_gpu dotnet /home/heimindanger/ipfs-uploader/Uploader.Web/bin/Release/netcoreapp2.0/publish/Uploader.Web.dll" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo
  when: ansible_distribution_major_version == "8"

- name: Starting ipfs-uploader in afforementioned tmux session as heimindanger as a CPU instance
  command: tmux send -t upldr.0 "ASPNETCORE_ENVIRONMENT=prod_cpu dotnet /home/heimindanger/ipfs-uploader/Uploader.Web/bin/Release/netcoreapp2.0/publish/Uploader.Web.dll" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo
  when: ansible_distribution_major_version == "9"
