- name: Exporting environment variable for cpu hosts
  lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^ASPNETCORE_ENVIRONMENT=prodcpu'
        line: 'ASPNETCORE_ENVIRONMENT=prodcpu'
        create: true

- name: Copying and unzipping ipfs-uploader from local host.
  copy:
    src: ipfs-uploader.zip
    dest: /home/heimindanger/
    mode: 0777
  become_user: heimindanger
  become_method: sudo
  notify: Installing new ipfs-uploader

- name: Changeing permissions on ipfs-uploader directory making it heimindanger:dtube 0770
  file:
    path: /home/heimindanger/ipfs-uploader/
    owner: heimindanger
    group: dtube
    mode: 0770
    recurse: yes

- name: Starting upldr tmux session as heimindanger (may fail when session already exists)
  command: tmux new -d -s upldr
  become: true
  become_user: heimindanger
  become_method: sudo
  ignore_errors: yes


- name: Moving tmux session working directory to /home/heimindanger/ipfs-uploader/
  command: tmux send -t upldr.0 "cd /home/heimindanger/ipfs-uploader/" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo

- name: Starting ipfs-uploader in afforementioned tmux session as heimindanger
  command: tmux send -t upldr.0 "dotnet /home/heimindanger/ipfs-uploader/bin/release/netcoreapp2.0/Uploader.dll" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo
