- name: Getting ipfs-uploader from ipfs
  command: ipfs get QmRZRoVJzbauu2fGaaXfTZfJsE4kqJwBuge3dM7FynHhj5 -o /home/heimindanger/ipfs-uploader/bin/
  args:
    creates: /home/heimindanger/ipfs-uploader/
  become_user: heimindanger
  become_method: sudo
  ignore_errors: yes

- name: Changeing permissions on ipfs-uploader directory making it heimindanger:dtube 0770
  file:
    path: /home/heimindanger/ipfs-uploader/
    owner: heimindanger
    group: dtube
    mode: 0770
    recurse: yes

- name: Starting upldr tmux session as heimindanger (may fail when session already exists)
  command: tmux new -d -s upldr
  become: true
  become_user: heimindanger
  become_method: sudo
  ignore_errors: yes


- name: Moving tmux session working directory to /home/heimindanger/ipfs-uploader/
  command: tmux send -t upldr.0 "cd /home/heimindanger/ipfs-uploader/" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo

- name: Starting ipfs-uploader in afforementioned tmux session as heimindanger
  command: tmux send -t upldr.0 "dotnet /home/heimindanger/ipfs-uploader/bin/release/netcoreapp2.0/Uploader.dll" ENTER
  become: true
  become_user: heimindanger
  become_method: sudo
